spring:
  application:
    name: vanilla
management:
  context_path: /admin
logging:
  level:
    org.springframework.security: DEBUG

server.port: 8090

security.oauth2.resource.userInfoUri: http://localhost:8080/user
security.oauth2.client.client-id: my-client-with-secret
security.oauth2.client.client-secret: secret
security.oauth2.resource.tokenInfoUri: http://localhost:8080/oauth/check_token
# security.oauth2.resource.id: service -- Throws arror message